---
functional:
  - У пользователя должна быть возможность авторизации
  - Пользователь может играть с ботом
  - Пользователь может играть с другом по ссылке
  - Пользователь может играть с любым другим пользователем
#требования из документации раздел механика игры
  - У пользователя должна быть возможность создать игру 
  - После создания игры пользователем у других пользователей должна появиться возможность подключиться к игре 
  - После подключения второго пользователя, обоих пользователей должно перекинуть в саму игру 
  - Оба пользователя должны видеть два редактора слева -свой редактор справа - соперника.
  - Наверху находится время игры и ниже - задание 
  - Каждый игрок видит код своего соперника в режиме он-лайн.
  - Каждый игрок имеет кнопку check для проверки своего решения. 
  - количество попыток проверки неограниченно.
  - Если вдруг один из игроков вылетел из игры, второй может продолжать играть. 
  - Первый в любой момент игры, пока она не закончена, может переподключиться в игру.
  - Игра пока может длиться неограниченное время.
  - Когда один из игроков находит верное решение, обоим игрокам высвечивается модальное окно, где написано, кто является победителем этой игры.
  - Победитель-игрок может выйти из игры по нажатию кнопки exit которая у него появилась. 
  - Кнопка "check" у победителя-игрока более неактивна, но он может остаться и посмотреть ещё раз на свой код.
  - проигравший тоже может выйти из игры
  -  проигравший может доиграть до конца.
  - Когда оба игрока вышли, игра считается полностью законченной и удаляется из памяти.
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - упоминание о политике конфиденциальности
